{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
  labels:
    app: ecommerce-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: ecommerce-backend
{{- end }}
