replicaCount: 1

image:
  repository: dnarlakanti/ecommerce-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ecommerce.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

env:
  - name: BACKEND_URL
    value: "http://ecommerce-backend:5000"
