replicaCount: 1

image:
  repository: dnarlakanti/ecommerce-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: DATABASE_URL
    value: "postgresql://ecommerce:password@ecommerce-postgres:5432/ecommerce"
